image: python:3.7-slim

stages:
    -   test
#    -   build
#    -   docs

python3.5:
    image:
        python:3.5-slim
    before_script:
        -   python -m pip install -r requirements.txt
    script:
        -   python test.py
    stage:
        test

python3.6:
    image:
        python:3.6-slim
    before_script:
        -   python -m pip install -r requirements.txt
    script:
        -   python test.py
    stage:
        test

python3.7:
    image:
        python:3.7-slim
    before_script:
        -   python -m pip install -r requirements.txt
    script:
        -   python test.py
    stage:
        test

#bdist_wheel:
#    stage:
#        build
#    script:
#        -   python setup.py bdist_wheel
#    artifacts:
#        paths:
#            -   dist/*.whl
